Repository colpal/dataeng-container-tools, pull requests merged in 2025-06, with the labels that each got.

#192 feature: SF Module
  dataeng_container_tools/modules/__init__.py
  dataeng_container_tools/modules/snowflake/__init__.py
  dataeng_container_tools/modules/snowflake/sf.py
Labels: feature

#193 ci: Update release-drafter branches and config settings
  .github/release-drafter.yaml
  .github/workflows/release-drafter.yaml
Labels: bug, chore

#198 Misc Cleanup and Tests
  .gitignore
  dataeng_container_tools/__init__.py
  dataeng_container_tools/modules/__init__.py
  dataeng_container_tools/modules/datastore/__init__.py
  dataeng_container_tools/modules/datastore/datastore.py
  dataeng_container_tools/modules/download/download.py
  dataeng_container_tools/modules/ds/__init__.py
  dataeng_container_tools/modules/gcs/__init__.py
  dataeng_container_tools/modules/gcs/gcs.py
  pyproject.toml
  setup.py
  tests/__init__.py
  tests/conftest.py
  tests/download/__init__.py
  tests/download/test_download_to_file.py
  tests/gcs/__init__.py
  tests/gcs/test_gcs_download.py
  tests/gcs/test_gcs_mixed.py
  tests/gcs/test_gcs_upload.py
  tests/gcs/test_gcs_utils.py
Labels: dependencies

#202 feature: Add detection for running locally
  dataeng_container_tools/__init__.py
  dataeng_container_tools/container_utils.py
Labels: feature

#201 Updated readme (unfinished)
  README.md
Labels: documentation
